export const FORM_STATUS = 'FORM_STATUS';
export const AJAX_LOADING = 'AJAX_LOADING';
export const GET_CAKE_SUCCESS = 'GET_CAKE_SUCCESS';
export const GET_CAKES_SUCCESS = 'GET_CAKES_SUCCESS';
export const CREATE_CAKE_SUCCESS = 'CREATE_CAKE_SUCCESS';
export const UPDATE_CAKE_SUCCESS = 'UPDATE_CAKE_SUCCESS';
export const DELETE_CAKE_SUCCESS = 'DELETE_CAKE_SUCCESS';
